files:
  - source: /docs/books/**/*.md
    ignore:
      - '*.es.md'
      - '*.fr.md'
      - '*.zh.md'
      - '*.it.md'
      - '*.ja.md'
      - '*.pt.md'
      - '*.en.md'
      - '*.sv.md'
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
