---
site_name: 'Rocky Linux Documentation'
site_url: 'https://docs.rockylinux.org'
docs_dir: 'docs/'
repo_url: https://github.com/hbjydev/rldocs
repo_name: rocky-linux/documentation
edit_uri: 'edit/main/docs/'

nav:
  - '...'

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: theme
  font:
    text: Red Hat Text
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
  - localsearch
  - awesome-pages
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français
        es: Español
        zh: 简体中文
  # - tags

extra: 
  generator: false
