---
site_name: 'Rocky Linux Documentation'
site_url: 'https://docs.rockylinux.org'
docs_dir: 'docs/'
repo_url: https://github.com/hbjydev/rldocs
repo_name: rocky-linux/documentation
edit_uri: 'edit/main/docs/'

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: theme
  font:
    text: Red Hat Text
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  logo: assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - localsearch
  - awesome-pages
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français
        es: Español
        zh: 简体中文
  # - tags

extra: 
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rocky_linux
    - icon: fontawesome/brands/github
      link: https://github.com/rocky-linux
    - icon: fontawesome/brands/gitlab
      link: https://git.rockylinux.org
    - icon: material/home
      link: https://rockylinux.org

copyright: Copyright &copy; 2021 The Rocky Enterprise Software Foundation